### ISSUE TITLE
Ensure TERRA REF backed up to TACC

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/data#12]
* first priority is season 3-9 raw_data/ plus Level_1/laser3Dply
   * in raw_data, you can skip 3DScannerRawDataTopTmp, UAV, ua-mac, TestIn, 3DTest, scanner3DLowerOnWestSide, FLIR_TG167_handheld, phenotractor
* for seasons 1-2, there is no raw_data folder
   * back up raw_data/irrigation and Level_1 for this season
* for data outside season date ranges, call it 'noseason'
* other derived data are lower priority b/c they can be re-generated (albiet slowly)
* create a table that lists locations and content of each tar file 
   * tar filename + tarfile md5 and for each file: directory path, filename, file size
* use same tar as Sean used for archiving (not the backup which was less structured)

**Progress and notes:** https://hackmd.io/@julianp-diag/SJRDa0vSw

## Currently on Ranch@TACC:

- [ ] Season 9
  - [ ] Level 0
    - [x] VNIR
    - [x] stereoTop
    - [x] scanner3DTop
    - [x] SWIR
    - [x] sensor_group
  - [ ] Level 1
  - [ ] Level 2
  - [ ] Level 3

- [ ] Season 8
  - [ ] Level 0
    - [x] VNIR
    - [x] stereoTop
    - [x] scanner3DTop
    - [x] SWIR
    - [ ] sensor_group
  - [ ] Level 1
  - [ ] Level 2
  - [ ] Level 3
  
- [ ] Season 7
  - [ ] Level 0
    - [x] VNIR
    - [ ] stereoTop
    - [x] scanner3DTop
    - [x] SWIR
    - [x] sensor_group
  - [ ] Level 1
  - [ ] Level 2
  - [ ] Level 3
  
- [ ] Season 6
  - [ ] Level 0
    - [ ] VNIR
    - [x] stereoTop
    - [x] scanner3DTop
    - [ ] SWIR
    - [ ] sensor_group (retrying tar step)
  - [ ] Level 1
  - [ ] Level 2
  - [ ] Level 3
  
- [ ] Season 5
  - [ ] Level 0
    - [ ] VNIR
    - [x] stereoTop
    - [x] scanner3DTop
    - [ ] SWIR
    - [ ] sensor_group (FAILED)
  - [ ] Level 1
  - [ ] Level 2
  - [ ] Level 3
  
- [ ] Season 4
  - [ ] Level 0
    - [ ] VNIR
    - [ ] stereoTop (in progress: transferring)
    - [ ] scanner3DTop (in progress: transferring)
    - [ ] SWIR
    - [ ] sensor_group
  - [ ] Level 1
  - [ ] Level 2
  - [ ] Level 3
  
- [ ] Season 3
  - [ ] Level 0
    - [ ] VNIR
    - [ ] stereoTop
    - [ ] scanner3DTop
    - [ ] SWIR
    - [ ] sensor_group
  - [ ] Level 1
  - [ ] Level 2
  - [ ] Level 3
  
- [ ] Season 2
  - [ ] Level 0
    - [ ] VNIR
    - [ ] stereoTop
    - [ ] scanner3DTop
    - [ ] SWIR
    - [ ] sensor_group
  - [ ] Level 1
  - [ ] Level 2
  - [ ] Level 3
  
- [ ] Season 1
  - [ ] Level 0
    - [ ] VNIR
    - [ ] stereoTop
    - [ ] scanner3DTop
    - [ ] SWIR
    - [ ] sensor_group
  - [ ] Level 1
  - [ ] Level 2
  - [ ] Level 3
