### ISSUE TITLE
Create tar files for season 9 and and transfer to TACC (part 2)

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/data#17]
Preceding issue: https://github.com/AgPipeline/data/issues/16

**Task to do**

Create tar files for season 9 and transfer to TACC

**Reason**

[Ensure TERRA REF backed up to TACC and GDRIVE](https://github.com/AgPipeline/data/issues/12)

**Result**

- Tar files on TACC containing raw_data/ plus Level_1/laser3Dply for season 9
- Also on TACC: Matching '.md5' files containing the contents of the tar files with the md5 checksums

**Steps to take**

See detailed instructions: <https://hackmd.io/@julianp-diag/SkKtF09TI>

- [x] Push scripts to TERRA REF GitHub repo
  - See PR 88 on admin repo
- [x] Fix issues with tar script
    - [x] No .md5 files (known cause)
    - [x] Only created 7 tar files instead of 14 (unknown cause)
- [x] See if `pigz` makes it faster to tar, as reminded by @rbartelme 
- [x] Talk to Chad & Sean about how slow it is to tar files
- [ ] Divvy up TERRA-REF data archiving between managed/scripted (Also update TODO in sprint planning notes)

**Progress and notes**

<https://hackmd.io/@julianp-diag/SJRDa0vSw>

**Comment by julianpistorius** [comment]
Talked to Chad & Sean about the performance issue:

> Hi Chad and Sean,
> 
> Thanks for checking in. No, we are not done yet. We have run into a
> problem and I hope you might be able to help us.
> 
> Tarring of sensor data on the VM at NCSA seems to take about 10
> minutes per 50G. I've measured 2 hours and 15 minutes per 512GB tar
> file, or 4.5 hours per TB.
> 
> Assuming 300TB total amount of data to archive, it will take about
> 1400 hours (about 2 months) just for tarring.
> 
> This time does not include transferring the data to TACC using Globus.
> Transferring a tar file from NCSA to TACC is roughly three times
> faster than creating the tar file (about 45 minutes per tar file, or
> 1.5 hours per TB).
> 
> Note: I still have to confirm the 300TB number - it could be more.
> 
> I suspect we might be bottle-necked by the I/O speed of the RAID.
> During the tar process we are concurrently reading from, and writing
> to the same RAID. If we're bottle-necked by the RAID then creating tar
> files in parallel will not speed things up (but transferring tar files
> to TACC while creating tar files might be OK).
> 
> Assuming I'm right about the RAID, one option to speed up the tarring
> process is to add a fast scratch disk (ideally SSD) to that virtual
> machine. We can then use this scratch disk as the temporary location
> of the new tar files. Once the tar file is created we can either A.
> move it back to the RAID, or B. immediately transfer it from the
> scratch area to TACC (best option will depend on speed of moving the
> file back to RAID).
> 
> Tomorrow I am planning to test my hypothesis that separating reads and
> writes will speed up the tarring process.
> 
> Do you have any other ideas? Do you know if it's possible to add
> another (fast) disk to that machine? In the absence of any way to
> speed up the tarring, it could easily take 3 months to tar and
> transfer the files. If we can get the tarring to be as fast or faster
> than the Globus transfer speed, we could get 300TB off there in about
> three weeks.
> 
> Let me know if you have any questions.
> 
> Thanks again,
> Julian

On Tuesday Chad said:

> So, I'm certain that it is not the storage end. That is 2 DDN 12KX machines with 16 edr infinband connections across 4 dell r730's each with a 40g nic. It is probably the VM. I wil look at its configuration and see if there is some tuning on the linux side and on the hypervisor side that we can do to help the network performance. I didn't run an iperf on it after building it.

**Comment by Chris-Schnaufer** [comment]
@julianpistorius What's the status of this issue?

**Comment by julianpistorius** [comment]
Update:

- Chad provisioned new hardware with more cores & RAM
- After some authentication issues I was able to access it

Next steps:

- Benchmark the tar & transfer processes on the new hardware by the end of this week
- Fix issues with tar script

**Comment by julianpistorius** [comment]
The new hardware made almost no difference to how fast the tar files are created. It still takes over 2 hours per tar file.

```bash
clear; reset
mkdir -p ~/speed-test/cp-test
cat /terraref/users/scratch/archive_work/file_lists/raw_S9/ps2Top/ps2Top_split.P2 \
    | sed '#s#/$#' \
    | xargs -L 1 -I % bash -c "bash -c \"time cp -r % ~/speed-test/cp-test/\" && du -h --max-depth=1 ~/speed-test/cp-test && rm -rf ~/speed-test/cp-test/*"
```

I see times of around 5-6 seconds (sometimes 10 seconds) to copy 227MB of data from `/terraref` to my home directory.

So if we say 15 seconds to copy 1GB, that's about 2 hours to copy 512GB.

So I don't think adding a scratch drive would help. The bottleneck seems to be in the read-speed of the RAID to the machine creating the tar files.

**Comment by julianpistorius** [comment]
Update:

- Fixed problem with md5 files not being created
- Fixed problem with only half the tar files being created
- Ran into a problem with the Globus failing due to a problem with NFS
  - Started using `scp` to transfer files instead of Globus
  - Then had the same problem with plain `ls` in shell
  - Chad [said](https://terra-ref.slack.com/archives/G7Q3SQGC9/p1599776023012800): "the vm got evicted by the cluster for a few minutes for some reason. looking into it currently"

**Comment by julianpistorius** [comment]
Blocked from being able to continue due to disk being full: https://hackmd.io/@julianp-diag/SJRDa0vSw#2020-09-25

Moving this to backlog.

**Comment by julianpistorius** [comment]
Season 9 is finished, except for grouping the small sensors together. Have moved on to Season 8.
